apiVersion: v1
kind: Service
metadata:
  name: {{ print (include "jwt-token-service.fullname" .) "-api" }}
  labels:
    {{- include "jwt-token-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  ports:
    - port: {{ .Values.apiService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jwt-token-service.selectorLabels" . | nindent 4 }}
