apiVersion: v1
kind: Service
metadata:
  name: {{ print (include "jwt-token-service.fullname" .) "-jwks" }}
  labels:
    {{- include "jwt-token-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jwksService.type }}
  ports:
    - port: {{ .Values.jwksService.port }}
      targetPort: jwks
      protocol: TCP
      name: http
  selector:
    {{- include "jwt-token-service.selectorLabels" . | nindent 4 }}
