{{- $cert := genSelfSignedCert (include "jwt-token-service.fullname" .) nil nil 3650 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jwt-token-service.fullname" . }}
  labels:
    {{- include "jwt-token-service.labels" . | nindent 4 }}
type: Opaque
data:
  private.key: {{ $cert.Key | b64enc }}