name: Build and push image

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tests
        run: go test ./...

  build-and-push:
    needs: test
    env:
      CR_PAT: ${{ secrets.CR_PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build docker image
        run: |
          docker build . \
            --cache-from ghcr.io/hgochev/jwt-token-issuer:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t "ghcr.io/hgochev/jwt-token-issuer:${GITHUB_RUN_NUMBER}" \
            -t "ghcr.io/hgochev/jwt-token-issuer:latest"
      - name: Push docker image
        run: |
          echo $CR_PAT | docker login ghcr.io -u hgochev --password-stdin

          docker push "ghcr.io/hgochev/jwt-token-issuer:${GITHUB_RUN_NUMBER}"
          docker push "ghcr.io/hgochev/jwt-token-issuer:latest"
